Redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
end

Redditclone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Redditclone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  
  belongs_to :user,
    foreign_key: :author_id,
    class_name: :User
  
  # belongs_to :sub

  
  
  has_many :post_subs,
  foreign_key: :post_id,
  class_name: :PostSub,
  inverse_of: :post
  
  has_many :subs,
  through: :post_subs,
  source: :sub
  
end

Redditclone/app/models/post_sub.rb
class PostSub < ApplicationRecord
    # validates :pos
  belongs_to :post
  belongs_to :sub
end

Redditclone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  
  validates :title, :description, presence:true
  
  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User
   
   
   
  has_many :post_subs,
  foreign_key: :sub_id,
  class_name: :PostSub,
  inverse_of: :sub
  
  has_many :posts,
  through: :post_subs,
  source: :post
end

Redditclone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  attr_reader :password
  
  after_initialize :ensure_session_token
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def reset_session_token! 
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  has_many :subs,
  foreign_key: :moderator_id,
  class_name: :Sub
  
  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post
  
end

Redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery :exception
  helper_method :current_user, :logged_in?
  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
  
end

Redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new 
    @subs = Sub.all
    @post = Post.new
  end
  
  
  
  def show
    @post = Post.find(params[:id])
  end 
  
  def create 
    # debugger
    @post = Post.new(post_params)
    @post.author_id = current_user.id
        # debugger
    
    if @post.save 
      redirect_to posts_url 
    else 
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_url
    end
  end
  
  def update 
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else 
      flash[:errors] = @post.errors.full_messages
    end 
  end
  
  def index 
    @posts = Post.all
  end
  
  def edit 
    @post = Post.find(params[:id])
  end
  
  def destroy 
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.link)
  end
  
  private 
  def post_params 
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

Redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid username or password"]
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to new_session_url
  end
end

Redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_login,only: [:edit,:update]
  def new
    @sub = Sub.new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def edit
    @sub = Sub.find(params[:id])
  end
  
  
  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def index
    @subs = Sub.all
  end
  
  def show
    @sub = Sub.find(params[:id])
  end
  
  
  
  private
  def sub_params
    params.require(:sub).permit(:title,:description)
  end
end

Redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new 
    
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save 
      login(@user)
      redirect_to subs_url 
    else 
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Redditclone/app/helpers/application_helper.rb
module ApplicationHelper
end

Redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

Redditclone/app/helpers/sessions_helper.rb
module SessionsHelper
end

Redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

Redditclone/app/helpers/users_helper.rb
module UsersHelper
end

Redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if logged_in? %>
    <form  action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" name="" value="Sign Out">
    </form>
    <% end %>
    
    <% if flash[:errors] %>
    <% flash[:errors].each do |err| %>
    <%= err %>
    <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

Redditclone/app/views/posts/new.html.erb
<h2>Add Post</h2>
<form  action="<%= posts_url %>" method="post">
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label> Title
  <input type="text" name="post[title]" value=""></label>
  <label>URL
  <input type="text" name="post[url]" value=""></label>
  <label>Content
  <input type="text" name="post[content]" value=""></label>
  
  <br>
  
  Subs
  <br>
  <% @subs.each do |sub| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %>
  <br>
  
  <% end %>
  <input type="submit" name="" value="Create Post">
  
</form>

Redditclone/app/views/posts/show.html.erb
<%= @post.sub_id %>

Redditclone/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form  action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Title
  <input type="text" name="sub[title]" value="<%= @sub.title %>">
<label>Description
  <input type="text" name="sub[description]" value="<%= @sub.description %>">
</label>
<input type="submit" name="" value="Edit Sub">
</form>

Redditclone/app/views/subs/index.html.erb
<h2>All Subs</h2>

<% @subs.each do |sub| %>
<%= sub.title %>
<%= sub.description %>
<a href="<%= sub_url(sub) %>"> Details</a>
<a href="<%= edit_sub_url(sub) %>">Edit Sub</a>
<br>
<% end %>

<a href="<%= new_sub_url %>">New Sub</a>

Redditclone/app/views/subs/new.html.erb
<h2>New Sub</h2>

<form  action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Title
  <input type="text" name="sub[title]" value="">
<label>Description
  <input type="text" name="sub[description]" value="">
</label>
<input type="submit" name="" value="Create Sub">
</form>

Redditclone/app/views/subs/show.html.erb
Title:<%= @sub.title %>
<br>
Description:<%= @sub.description %>



  
<h2>All Posts</h2>
<% @sub.posts.each do |post|%>

Title:<%= post.title %>
URL:<%= post.url %>
Content:<%= post.content %>
<br>
<% end %>

<a href="<%= new_post_url %>">Make New Post</a>

Redditclone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" 
  value="<%= form_authenticity_token %>">
  
  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>
  
  <label>
    Password
    <input type="text" name="user[password]" value="">
  </label>
  
  <input type="submit" name="" value="Sign Up">
  
  
</form>